### ISSUE TITLE
Any chance for a Fabric port?

### ISSUE THREAD

**Issue by RDKRACZ** [illusivesoulworks/diet#94]
### What is the new feature or improvement?

Some of your mods are already ported that's why I'm asking.

**Comment by TheIllusiveC4** [comment]
I'm hesitant to do a Fabric port because there's already a mod that accomplishes this basic function, Nourish, on Fabric.

**Comment by RDKRACZ** [comment]
Yes, but it looks like it's not updated anymore and the author doesn't respond to questions about 1.17, even a PR with a translation from  Oct 1 is not merged. Your UI textures are also better.

**Comment by Havio1** [comment]
Hate to necropost, but I also would love a Fabric port for this mod, it would go really well with a modpack I put together for my friends and I.

**Comment by TheIllusiveC4** [comment]
Diet for 1.19.2 is out now for Fabric (and Quilt).
